// Generates `projects/demo/src/app/examples/_sources.generated.ts` — a map of
// example slug → verbatim TypeScript source. The source is rendered (and
// highlighted) at runtime by shikidown. Wired via npm prestart / prebuild.
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const examplesDir = join(here, "..", "projects", "demo", "src", "app", "examples");
const outFile = join(examplesDir, "_sources.generated.ts");

const SKIP = new Set(["registry.ts", "_sources.generated.ts"]);

const files = (await readdir(examplesDir)).filter(f => f.endsWith(".ts") && !SKIP.has(f)).sort();

const entries = [];
for (const file of files) {
  const slug = file.replace(/\.ts$/, "");
  const raw = await readFile(join(examplesDir, file), "utf8");
  entries.push(`  ${JSON.stringify(slug)}: ${JSON.stringify(raw)}`);
}

const out = `// AUTO-GENERATED by scripts/gen-code.mjs — do not edit by hand.
// Verbatim source of each example, baked in at build time so it can be shown
// (and highlighted by shikidown) on each example page.

export const SOURCES: Record<string, string> = {
${entries.join(",\n")}
};
`;

await writeFile(outFile, out, "utf8");
console.log(`[gen-code] wrote ${files.length} example sources → ${outFile}`);
